@echo off
:: ==============================================================
:: EXTRACTOR DE HARDWARE (Antigravity v45 - Progress UI & Disk Types)
:: ==============================================================
title QA Criterio Digital v45
cls
echo [1/5] Iniciando sistema (v45)...

:: --- PERMISSIONS ---
reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam" /v Value /t REG_SZ /d Allow /f >nul 2>&1
reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\microphone" /v Value /t REG_SZ /d Allow /f >nul 2>&1

:: --- TEMP FILES ---
set "WIFIXML=%TEMP%\wifi_temp.xml"
set "BATTXML=%TEMP%\batt_temp_%RANDOM%.xml"
set "PSFILE=%~dp0temp_qa_v45.ps1"
set "LOGOFILE=%~dp0temp_logo.b64"
set "ERRFILE=%~dp0error_log.txt"

if exist "%PSFILE%" del "%PSFILE%"
if exist "%LOGOFILE%" del "%LOGOFILE%"
if exist "%WIFIXML%" del "%WIFIXML%"
if exist "%BATTXML%" del "%BATTXML%"
if exist "%ERRFILE%" del "%ERRFILE%"

echo [2/5] Escribiendo recursos...
:: --- LOGO ---
(
echo iVBORw0KGgoAAAANSUhEUgAAAhYAAAG2CAYAAAAjs8+gAAAAAXNSR0IArs4c6QAAIABJREFUeF7sfQdgVMX299ndJIQeEIg0FRRBQcS/2MsTkAeKHSl2QJoUy8OKz4YNRH12qWJHRJ/1iQXR9yxYABXFQrWgSJHeQrI733fOzNw7O3u3b7Kb5CzGTXbvnfKbuTO/OdUH/GIEGAFGgBFgBBgBRiBDCPgyVA4XwwgwAowAI8AIMAKMADCx4EnACDACjAAjwAgwAhlDgIlFxqDkghgBRoARYAQYAUaAiQXPAUaAEWAEGAFGgBFgYsFzgBFgBBgBRoARYAQyhgATi4xByQUxAowAI8AIMAKMACOQMQSYWGQMSi6IEWAEGAFGgBFgBJhY8BxgBBgBRoARYAQYgYwhwMQiY1ByQYwAI8AIMAKMACPAxILnACPACDACjAAjwAhkDAEmFhmDkgtiBBgBRoARYAQYASYWPAcYAQYAUaAEWAEGIGMIcDEImNQckGMACPACDACjAAjwMSC5wAjwAgwAowAI8AIZAwBJhYZg5ILYgQYAUaAEWAEGAEmFjwHGAFGgBFgBBgBRiBjCDCxyBiUXBAjwAgwAowAI8AIMLHgOcAIMAKMACPACDACGUOAiUXGoOSCGAFGgBFgBBgBRoCJBc8BRoARYAQYAUaAEcgYAkwsMgYlF8QIMAKMACPACDACTCx4DjACjAAjwAgwAoxAxhBgYpExKLkgRoARYAQYAUaAEWBiwXOAEWAEGAFGgBFgBDKGABOLjEHJBTECjAAjwAgwAowAEwueA4wAI8AIMAKMACOQMQSYWGQMSi6IEWAEGAFGgBFgBJhY8BxgBBgBRoARYAQYgYwhwMQiY1ByQYwAI8AIMAKMACPAxILnACPACDACjAAjwAhkDAEmFhmDkgtiBBgBRoARYAQYASYWPAcYAQYAUaAEWAEGIGMIcDEImNQckGMACPACDACjAAjwMSC5wAjwAgwAowAI8AIZAwBJhYZg5ILYgQYAUaAEWAEGAEmFjwHGAFGgBFgBBgBRiBjCDCxyBiUXBAjwAgwAowAI8AIMLHgOcAIMAKMACPACDACGUOAiUXGoOSCGAFGgBFgBBgBRoCJBc8BRoARYAQYAUaAEcgYAkwsMgYlF8QIMAKMACPACDACTCx4DjACjAAjwAgwAoxAxhBgYpExKLkgRoARYAQYAUaAEWBiwXOAEWAEGAFGgBFgBDKGABOLjEHJBTECjAAjwAgwAowAEwueA4wAI8AIMAKMACOQMQSYWGQMSi6IEWAEGAFGgBFgBJhY8BxgBBgBRoARYAQYgYwhwMQiY1ByQYwAI8AIMAKMACPAxILnACPACDACjAAjwAhkDAEmFhmDkgtiBBgBRoARYAQYASYWPAcYAQYAUaAEWAEGIGMIcDEImNQckGMACPACDACjAAjwMSC5wAjwAgwAowAI8AIZAwBJhYZg5ILYgQYAUaAEWAEGAEmFjwHGAFGgBFgBBgBRiBjCDCxyBiUXBAjwAgwAowAI8AIMLHgOcAIMAKMACPACDACGUOAiUXGoOSCGAFGgBFgBBgBRoCJBc8BRoARYAQYAUaAEcgYAkwsMgYlF8QIMAKMACPACDACTCx4DjACjAAjwAgwAoxAxhBgYpExKLkgRoARYAQYAUaAEWBiwXOAEWAEGAFGgBFgBDKGABOLjEHJBTECjAAjwAgwAowAEwueA4wAI8AIMAKMACOQMQSYWGQMSi6IEWAEGAFGgBFgBJhY8BxgBBgBRoARYAQYgYwhwMQiY1ByQYwAI8AIMAKMACPAxILnACPACDACjAAjwAhkDAEmFhmDkgtiBBgBRoARYAQYASYWPAcYAQYAUaAEWAEGIGMIcDEImNQckGMACPACDACjAAjwMSC5wAjwAgwAowAI8AIZAwBJhYZg5ILYgQYAUaAEWAEGAEmFjwHGAFGgBFgBBgBRiBjCDCxyBiUXBAjwAgwAowAI8AIMLHgOcAIMAKMACPACDACGUOAiUXGoOSCGAFGgBFgBBgBRoCJBc8BRoARYAQYAUaAEcgYAkwsMgYlF8QIMAKMACPACDACTCx4DjACjAAjwAgwAoxAxhBgYpExKLkgRoARYAQYAUaAEWBiwXOAEWAEGAFGgBFgBFYs3bt
) > "%LOGOFILE%"

:: --- WIFI & BATT ---
(echo ^<?xml version="1.0"?^>^<WLANProfile xmlns="http://www.microsoft.com/networking/WLAN/profile/v1"^>^<name^>RedCriterio^</name^>^<SSIDConfig^>^<SSID^>^<hex^>526564437269746572696F^</hex^>^<name^>RedCriterio^</name^>^</SSID^>^</SSIDConfig^>^<connectionType^>ESS^</connectionType^>^<connectionMode^>auto^</connectionMode^>^<MSM^>^<security^>^<authEncryption^>^<authentication^>WPA2PSK^</authentication^>^<encryption^>AES^</encryption^>^<useOneX^>false^</useOneX^>^</authEncryption^>^<sharedKey^>^<keyType^>passPhrase^</keyType^>^<protected^>false^</protected^>^<keyMaterial^>Contraseñacriterio1998^</keyMaterial^>^</sharedKey^>^</security^>^</MSM^>^</WLANProfile^>) > "%WIFIXML%"
netsh wlan add profile filename="%WIFIXML%" >nul 2>&1
netsh wlan connect name="RedCriterio" >nul 2>&1
powercfg /batteryreport /xml /output "%BATTXML%" >nul 2>&1

echo [3/5] Compilando logica (V45 - Version Header)...
:: --- POWERSHELL SCRIPT ---
echo $ErrorActionPreference = 'Stop' >> "%PSFILE%"
echo try { >> "%PSFILE%"
echo     $scriptPath = '%~dp0'; $errFile = '%ERRFILE%'; $logoFile = '%LOGOFILE%' >> "%PSFILE%"
echo     Add-Type -AssemblyName System.Windows.Forms >> "%PSFILE%"
echo     Add-Type -AssemblyName System.Drawing >> "%PSFILE%"
echo     try { Add-Type -AssemblyName System.Speech } catch {} >> "%PSFILE%"
echo     $BATTXML = '%BATTXML%' >> "%PSFILE%"
echo. >> "%PSFILE%"
echo     # --- THREAD SAFE STORAGE --- >> "%PSFILE%"
echo     $syncHash = [hashtable]::Synchronized(@{}) >> "%PSFILE%"
echo     $syncHash.Status = "Iniciando..." >> "%PSFILE%"
echo. >> "%PSFILE%"
echo     # --- HARDWARE SCANNER LOGIC --- >> "%PSFILE%"
echo     $scriptBlock = { >> "%PSFILE%"
echo         param($res, $battXml) >> "%PSFILE%"
echo         try { >> "%PSFILE%"
echo             $res.Log = "Iniciando..."; >> "%PSFILE%"
echo             $res.Status = "Analizando Sistema..."; >> "%PSFILE%"
echo             try { $bios = Get-CimInstance Win32_BIOS; $res.Serial = $bios.SerialNumber } catch { $res.Serial = "Error" } >> "%PSFILE%"
echo             try { $cs = Get-CimInstance Win32_ComputerSystem; $res.Brand=$cs.Manufacturer; $res.Model=$cs.Model } catch { $res.Brand="Gen"; $res.Model="Gen" } >> "%PSFILE%"
echo             try { $res.UUID = (Get-CimInstance Win32_ComputerSystemProduct).UUID } catch { $res.UUID = "Error" } >> "%PSFILE%"
echo             $res.Status = "Analizando CPU..."; >> "%PSFILE%"
echo             try { $cpu = Get-CimInstance Win32_Processor; $ghz = [math]::Round($cpu.MaxClockSpeed / 1000, 2); $res.CPU = "$($cpu.Name) (Max $ghz GHz)" } catch { $res.CPU = "Error CPU" } >> "%PSFILE%"
echo             # RAM >> "%PSFILE%"
echo             $res.Status = "Analizando RAM..."; >> "%PSFILE%"
echo             try { $res.RamGB = [math]::Round((Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory/1GB) } catch { $res.RamGB = "?" } >> "%PSFILE%"
echo             try { $rLog=@(); Get-CimInstance Win32_PhysicalMemory ^| ForEach{$gb=[math]::Round($_.Capacity/1GB); $rLog+="$gb GB @ $($_.Speed)MHz"}; $res.RamDet = $rLog -join ' + ' } catch { $res.RamDet = "Error" } >> "%PSFILE%"
echo             # DISKS (V43/44 Fixed Type) >> "%PSFILE%"
echo             $res.Status = "Analizando Discos..."; >> "%PSFILE%"
echo             try { >> "%PSFILE%"
echo                 $dLog=@() >> "%PSFILE%"
echo                 $disks = Get-PhysicalDisk ^| Sort DeviceId >> "%PSFILE%"
echo                 if($disks){ $disks ^| ForEach{$gb=[math]::Round($_.Size/1GB); $t=$_.MediaType; $b=$_.BusType; if($b -eq 'NVMe'){$t="NVMe SSD"}elseif($t -eq 'SSD'){$t="SATA SSD"}; $dLog+="- $($_.FriendlyName) ($gb GB) [$t]"} } >> "%PSFILE%"
echo                 else { Get-CimInstance Win32_DiskDrive ^| ForEach{$gb=[math]::Round($_.Size/1GB); $dLog+="- $($_.Model) ($gb GB)"} } >> "%PSFILE%"
echo                 $res.Disks = $dLog >> "%PSFILE%"
echo             } catch { $res.Disks = "Error Disk" } >> "%PSFILE%"
echo             # GPU >> "%PSFILE%"
echo             $res.Status = "Analizando Video..."; >> "%PSFILE%"
echo             try { >> "%PSFILE%"
echo                 $gLog=@() >> "%PSFILE%"
echo                 Get-CimInstance Win32_VideoController ^| ForEach { >> "%PSFILE%"
echo                     $ram = $_.AdapterRAM >> "%PSFILE%"
echo                     $name = $_.Name >> "%PSFILE%"
echo                     $vramStr = "" >> "%PSFILE%"
echo                     if ($ram -ge 1GB) { >> "%PSFILE%"
echo                         $val = [math]::Round($ram / 1GB, 2) >> "%PSFILE%"
echo                         $vramStr = "$val GB" >> "%PSFILE%"
echo                     } elseif ($ram -gt 0) { >> "%PSFILE%"
echo                         $val = [math]::Round($ram / 1MB, 0) >> "%PSFILE%"
echo                         $vramStr = "$val MB" >> "%PSFILE%"
echo                     } else { >> "%PSFILE%"
echo                         $vramStr = "Compartida" >> "%PSFILE%"
echo                     } >> "%PSFILE%"
echo                     if ($name -match "Intel" -or $name -match "Iris" -or $name -match "UHD") { >> "%PSFILE%"
echo                         $vramStr = "128 MB (Integrada)" >> "%PSFILE%"
echo                     } elseif ($name -match "Radeon.*Graphics" -or $name -match "AMD.*Graphics") { >> "%PSFILE%"
echo                         $vramStr = "$vramStr (Integrada)" >> "%PSFILE%"
echo                     } >> "%PSFILE%"
echo                     $gLog += "$name (VRAM: $vramStr)" >> "%PSFILE%"
echo                 } >> "%PSFILE%"
echo                 $res.GPU = $gLog >> "%PSFILE%"
echo             } catch { $res.GPU = "Error GPU" } >> "%PSFILE%"
echo             # LICENSES >> "%PSFILE%"
echo             $res.Status = "Verificando Licencias..."; >> "%PSFILE%"
echo             try { >> "%PSFILE%"
echo                 $os=Get-CimInstance Win32_OperatingSystem; $res.OS=$os.Caption; $res.WinStat="?"; $res.Office="No" >> "%PSFILE%"
echo                 $l=Get-CimInstance SoftwareLicensingProduct ^| Where{$_.PartialProductKey -and $_.Name -like "*Windows*"} ^| Select -First 1; if($l.LicenseStatus -eq 1){$res.WinStat="ACTIVADO"}else{$res.WinStat="NO (Estado: $($l.LicenseStatus))"} >> "%PSFILE%"
echo                 $o=Get-CimInstance SoftwareLicensingProduct ^| Where{$_.PartialProductKey -and $_.Name -like "*Office*"} ^| Select -First 1; if($o.LicenseStatus -eq 1){$res.Office="ACTIVADO"}else{$res.Office="INSTALADO (Estado: $($o.LicenseStatus))"} >> "%PSFILE%"
echo             } catch { $res.OS += " (Err Lic: $_)" } >> "%PSFILE%"
echo             # EXTRA >> "%PSFILE%"
echo             $res.Status = "Finalizando..."; >> "%PSFILE%"
echo             $res.Screen="Generico"; try{$v=Get-CimInstance Win32_VideoController ^| Select -First 1; if($v){$res.Screen="$($v.CurrentHorizontalResolution) x $($v.CurrentVerticalResolution)"}}catch{} >> "%PSFILE%"
echo             $pnp = Get-CimInstance Win32_PnpEntity >> "%PSFILE%"
echo             $res.Touch="NO"; if($pnp ^| Where-Object {$_.Name -like "*Touch screen*"}){$res.Touch="SI (Pantalla Tactil)"} >> "%PSFILE%"
echo             $res.Finger="NO"; if($pnp ^| Where-Object {$_.Name -match 'Fingerprint'}){$res.Finger="SI (Biometria)"} >> "%PSFILE%"
echo             # UPGRADE >> "%PSFILE%"
echo             try { >> "%PSFILE%"
echo                 $memArr = Get-CimInstance Win32_PhysicalMemoryArray; $memUsed = (Get-CimInstance Win32_PhysicalMemory).Count; $memSlots = $memArr.MemoryDevices; $memMax = [math]::Round($memArr.MaxCapacity / 1024 / 1024); $memFree = $memSlots - $memUsed >> "%PSFILE%"
echo                 $res.ExpRam = "$memUsed instalados / $memSlots totales (Max $memMax GB)" >> "%PSFILE%"
echo             } catch { $res.ExpRam = "?" } >> "%PSFILE%"
echo             try { $res.ExpDisk = "Desconocido (Verificar visualmente)"; $s=Get-CimInstance Win32_SystemSlot^|Where{$_.SlotDesignation -match 'M.2' -or $_.SlotDesignation -match 'SSD'}; if($s){$f=($s^|Where{$_.CurrentUsage -eq 3}).Count; $res.ExpDisk="Slots M.2: $($s.Count) Total ^| $f Disponibles"} } catch {} >> "%PSFILE%"
echo             # BATTERY >> "%PSFILE%"
echo             $m1="--"; $m3="--" >> "%PSFILE%"
echo             if(Test-Path $battXml){try{[xml]$x=Get-Content $battXml; $b=@($x.BatteryReport.Batteries.Battery)[-1]; $f=$b.FullChargeCapacity; $d=$b.DesignCapacity; if($d-gt 0){$p=[math]::Round(($f/$d)*100); $m1="$p%% (Ciclos: $($b.CycleCount))"}else{$m1="Leido"}}catch{}} >> "%PSFILE%"
echo             try{$w=Get-CimInstance Win32_Battery; if($w){$m3="$($w.EstimatedChargeRemaining)%%"}}catch{} >> "%PSFILE%"
echo             $res.BattM1=$m1; $res.BattM3=$m3 >> "%PSFILE%"
echo. >> "%PSFILE%"
echo             $res.Status = "Done" >> "%PSFILE%"
echo         } catch { $res.Status = "Error: $_" } >> "%PSFILE%"
echo     } >> "%PSFILE%"
echo. >> "%PSFILE%"
echo     # --- START BG THREAD --- >> "%PSFILE%"
echo     $runspace = [powershell]::Create() >> "%PSFILE%"
echo     $runspace.AddScript($scriptBlock) ^| Out-Null >> "%PSFILE%"
echo     $runspace.AddArgument($syncHash) ^| Out-Null >> "%PSFILE%"
echo     $runspace.AddArgument($BATTXML) ^| Out-Null >> "%PSFILE%"
echo     $handle = $runspace.BeginInvoke() >> "%PSFILE%"
echo. >> "%PSFILE%"
echo     # --- GUI HELPERS --- >> "%PSFILE%"
echo     function New-RoundedButton([string]$t, [int]$x, [int]$y, [int]$w, [int]$h, [System.Drawing.Color]$bc, [System.Drawing.Color]$fc) { >> "%PSFILE%"
echo         $b = New-Object System.Windows.Forms.Button >> "%PSFILE%"
echo         $b.Text = $t; $b.Left=$x; $b.Top=$y; $b.Width=$w; $b.Height=$h >> "%PSFILE%"
echo         $b.BackColor=$bc; $b.ForeColor=$fc; $b.FlatStyle='Flat'; $b.FlatAppearance.BorderSize=0 >> "%PSFILE%"
echo         $b.Font = New-Object System.Drawing.Font("Segoe UI", 12, [System.Drawing.FontStyle]::Bold) >> "%PSFILE%"
echo         $path = New-Object System.Drawing.Drawing2D.GraphicsPath >> "%PSFILE%"
echo         $rad = 20 >> "%PSFILE%"
echo         $path.AddArc(0, 0, $rad, $rad, 180, 90) >> "%PSFILE%"
echo         $path.AddArc($w-$rad, 0, $rad, $rad, 270, 90) >> "%PSFILE%"
echo         $path.AddArc($w-$rad, $h-$rad, $rad, $rad, 0, 90) >> "%PSFILE%"
echo         $path.AddArc(0, $h-$rad, $rad, $rad, 90, 90) >> "%PSFILE%"
echo         $path.CloseFigure() >> "%PSFILE%"
echo         $b.Region = New-Object System.Drawing.Region($path) >> "%PSFILE%"
echo         return $b >> "%PSFILE%"
echo     } >> "%PSFILE%"
echo. >> "%PSFILE%"
echo     # --- BUILD FORM --- >> "%PSFILE%"
echo     $bg   = [System.Drawing.Color]::FromArgb(17,24,39) >> "%PSFILE%"
echo     $card = [System.Drawing.Color]::FromArgb(31,41,55) >> "%PSFILE%"
echo     $text = [System.Drawing.Color]::FromArgb(243,244,246) >> "%PSFILE%"
echo     $acc  = [System.Drawing.Color]::FromArgb(37,99,235) >> "%PSFILE%"
echo     $warn = [System.Drawing.Color]::FromArgb(239,68,68) >> "%PSFILE%"
echo     $suc  = [System.Drawing.Color]::FromArgb(34,197,94) >> "%PSFILE%"
echo     $neu  = [System.Drawing.Color]::FromArgb(156,163,175) >> "%PSFILE%"
echo     try { Add-Type -AssemblyName System.Speech } catch {} >> "%PSFILE%"
echo     $synth = New-Object -TypeName System.Speech.Synthesis.SpeechSynthesizer >> "%PSFILE%"
echo. >> "%PSFILE%"
echo     $form = New-Object System.Windows.Forms.Form >> "%PSFILE%"
echo     $form.Text = "QA Criterio Digital"; $form.Size = New-Object System.Drawing.Size(420,620) >> "%PSFILE%"
echo     $form.StartPosition = "CenterScreen"; $form.BackColor = $bg; $form.ForeColor = $text; $form.FormBorderStyle = "FixedDialog"; $form.MaximizeBox = $false >> "%PSFILE%"
echo     $pnlTop = New-Object System.Windows.Forms.Panel; $pnlTop.Height = 80; $pnlTop.Dock = "Top"; $pnlTop.BackColor = $bg; $form.Controls.Add($pnlTop) >> "%PSFILE%"
echo     try { $b64 = Get-Content $logoFile -Raw; $ms = New-Object System.IO.MemoryStream([Convert]::FromBase64String($b64)); $logoImg = [System.Drawing.Image]::FromStream($ms); $pbLogo = New-Object System.Windows.Forms.PictureBox; $pbLogo.Image=$logoImg; $pbLogo.SizeMode="Zoom"; $pbLogo.Height=70; $pbLogo.Width=200; $pbLogo.Left=110; $pbLogo.Top=10; $pnlTop.Controls.Add($pbLogo) } catch { $lblLogo = New-Object System.Windows.Forms.Label; $lblLogo.Text = "CRITERIO"; $lblLogo.Location = New-Object System.Drawing.Point(130, 20); $pnlTop.Controls.Add($lblLogo) } >> "%PSFILE%"
echo     $pnlCard = New-Object System.Windows.Forms.Panel; $pnlCard.Size = New-Object System.Drawing.Size(380, 460); $pnlCard.Location = New-Object System.Drawing.Point(12, 90); $pnlCard.BackColor = $card; $form.Controls.Add($pnlCard) >> "%PSFILE%"
echo     $lblMain = New-Object System.Windows.Forms.Label; $lblMain.Text = "PRUEBA 1/3: CAMARA"; $lblMain.Font = New-Object System.Drawing.Font("Segoe UI", 14, [System.Drawing.FontStyle]::Bold); $lblMain.ForeColor = $acc; $lblMain.Size = New-Object System.Drawing.Size(360, 30); $lblMain.TextAlign = "MiddleCenter"; $lblMain.Location = New-Object System.Drawing.Point(10, 20); $pnlCard.Controls.Add($lblMain) >> "%PSFILE%"
echo     $lblSub = New-Object System.Windows.Forms.Label; $lblSub.Text = "Iniciando..."; $lblSub.Size = New-Object System.Drawing.Size(340, 60); $lblSub.TextAlign = "MiddleCenter"; $lblSub.Location = New-Object System.Drawing.Point(20, 60); $lblSub.ForeColor = $text; $pnlCard.Controls.Add($lblSub) >> "%PSFILE%"
echo     $btn = New-RoundedButton "INICIAR" 40 150 300 50 $acc "White"; $pnlCard.Controls.Add($btn) >> "%PSFILE%"
echo     $btnF = New-RoundedButton "FALLA" 40 220 300 40 $warn "White"; $btnF.Visible = $false; $pnlCard.Controls.Add($btnF) >> "%PSFILE%"
echo     $btnS = New-RoundedButton "OMITIR" 100 380 180 30 $card $neu; $btnS.FlatStyle="Flat"; $btnS.FlatAppearance.BorderColor=$neu; $pnlCard.Controls.Add($btnS) >> "%PSFILE%"
echo     $pb = New-Object System.Windows.Forms.ProgressBar; $pb.Size = New-Object System.Drawing.Size(340, 10); $pb.Location = New-Object System.Drawing.Point(20, 430); $pb.Style = "Continuous"; $pb.Value=0; $pnlCard.Controls.Add($pb) >> "%PSFILE%"
echo     $step=0; $rCam="?"; $rAud="?"; $rLit="?" >> "%PSFILE%"
echo     $timer = New-Object System.Windows.Forms.Timer; $timer.Interval = 500; $timer.Add_Tick({ >> "%PSFILE%"
echo         if($syncHash.Status -eq "Done") { $form.Text = "QA Criterio (Listo para generar)" } else { $form.Text = "QA Criterio (Analizando...)" } >> "%PSFILE%"
echo         if($script:step -eq 3 -and $syncHash.Status -ne "Done") { $lblSub.Text = $syncHash.Status } >> "%PSFILE%"
echo     }); $timer.Start() >> "%PSFILE%"
echo     function Next-Step { >> "%PSFILE%"
echo         $pb.Value = [math]::Min(100, $script:step * 33) >> "%PSFILE%"
echo         if ($script:step -eq 1) { $lblMain.Text="PRUEBA 2/3: AUDIO"; $lblSub.Text="Escuchando..."; $btn.Text="REPRODUCIR"; $btn.Visible=$true; $btnF.Visible=$false } >> "%PSFILE%"
echo         elseif ($script:step -eq 2) { $lblMain.Text="PRUEBA 3/3: HARDWARE"; $lblSub.Text="¿Luz de Teclado?"; $btn.Text="SI, TIENE"; $btnF.Text="NO TIENE"; $btnF.Visible=$true } >> "%PSFILE%"
echo         elseif ($script:step -eq 3) { >> "%PSFILE%"
echo             $lblMain.Text="GENERANDO REPORTE..."; $lblSub.Text="Espere un momento..."; $btn.Visible=$false; $btnF.Visible=$false; $btnS.Visible=$false >> "%PSFILE%"
echo             while($syncHash.Status -ne "Done"){ [System.Windows.Forms.Application]::DoEvents(); Start-Sleep -m 100 } >> "%PSFILE%"
echo             $res = $syncHash >> "%PSFILE%"
echo             $safe = $res.Model -replace '[^^a-zA-Z0-9]', '_' -replace '_+', '_' >> "%PSFILE%"
echo             $fName = "$($safe)_$(Get-Date -Format 'ddMM-HHmm')_$($res.Serial).txt" >> "%PSFILE%"
echo             $p = Join-Path $scriptPath $fName >> "%PSFILE%"
echo             $line="================================================================================" >> "%PSFILE%"
echo             $o=@(); $o+=$line; $o+="   CRITERIO DIGITAL  ^|  INFORME TECNICO  ^|  QA CERTIFICADO"; $o+=$line; $o+="FECHA   : " + (Get-Date).ToString("yyyy-MM-dd HH:mm"); $o+="" >> "%PSFILE%"
echo             $o+="[0] VERSION       :   v45 (Portable)"; $o+="" >> "%PSFILE%"
echo             $o+="[1] IDENTIFICACION"; $o+="    Marca       :   $($res.Brand)"; $o+="    Modelo      :   $($res.Model)"; $o+="    Serial      :   $($res.Serial)"; $o+="    UUID        :   $($res.UUID)"; $o+="    Sistema     :   $($res.OS) ($($res.WinStat))"; $o+="    Office      :   $($res.Office)"; $o+="" >> "%PSFILE%"
echo             $o+="[2] POTENCIA"; $o+="    CPU         :   $($res.CPU)"; $o+="    RAM Total   :   $($res.RamGB) GB ($($res.RamDet))"; $o+="    GPU         :   $($res.GPU)"; $o+="    Discos      :"; $res.Disks ^| ForEach { $o+="        $_" }; $o+="" >> "%PSFILE%"
echo             $o+="[3] CONECTIVIDAD"; $o+="    Pantalla    :   $($res.Screen)"; $o+="    Biometria   :   $($res.Finger)"; $o+="" >> "%PSFILE%"
echo             # $o+="[4] UPGRADE"; $o+="    RAM Slots   :   $($res.ExpRam)"; $o+="    Disk M.2    :   $($res.ExpDisk)"; $o+="" >> "%PSFILE%"
echo             $o+="[4] BATERIA"; $o+="    Salud XML   :   $($res.BattM1)"; $o+="    Carga Real  :   $($res.BattM3)"; $o+="" >> "%PSFILE%"
echo             $o+="[5] QA CHECKLIST"; $o+="    Camara      :   $rCam"; $o+="    Microfono   :   $rAud"; $o+="    Teclado Luz :   $rLit"; $o+=$line >> "%PSFILE%"
echo             $o ^| Out-File -FilePath $p -Encoding UTF8 >> "%PSFILE%"
echo             [System.Windows.Forms.MessageBox]::Show("Reporte Guardado!`n$fName") >> "%PSFILE%"
echo             $form.Close() >> "%PSFILE%"
echo         } >> "%PSFILE%"
echo     } >> "%PSFILE%"
echo     $btn.Add_Click({ >> "%PSFILE%"
echo         if($step -eq 0){ $lblSub.Text="Abre la app Camara..."; Start-Process "microsoft.windows.camera:"; $script:step=0.5; $btn.Text="CAMARA OK"; $btnF.Text="HAY FALLA"; $btnF.Visible=$true } >> "%PSFILE%"
echo         elseif($step -eq 0.5){ Stop-Process -Name "WindowsCamera" -ErrorAction SilentlyContinue; $script:rCam="OK"; $script:step=1; Next-Step } >> "%PSFILE%"
echo         elseif($step -eq 1){ if($synth){$synth.Speak("Audio Check")}; [console]::Beep(500,200); $lblSub.Text="¿Sono algo?"; $btn.Text="SI, SONO"; $btnF.Text="NO SONO"; $btnF.Visible=$true; $script:step=1.5 } >> "%PSFILE%"
echo         elseif($step -eq 1.5){ $script:rAud="OK"; $script:step=2; Next-Step } >> "%PSFILE%"
echo         elseif($step -eq 2){ $script:rLit="SI"; $script:step=3; Next-Step } >> "%PSFILE%"
echo     }) >> "%PSFILE%"
echo     $btnF.Add_Click({ >> "%PSFILE%"
echo         if($step -eq 0.5){ Stop-Process -Name "WindowsCamera" -ErrorAction SilentlyContinue; $script:rCam="FAIL"; $script:step=1; Next-Step } >> "%PSFILE%"
echo         elseif($step -eq 1.5){ $script:rAud="FAIL"; $script:step=2; Next-Step } >> "%PSFILE%"
echo         elseif($step -eq 2){ $script:rLit="NO"; $script:step=3; Next-Step } >> "%PSFILE%"
echo     }) >> "%PSFILE%"
echo     $btnS.Add_Click({ >> "%PSFILE%"
echo         if($step -le 0.5){ Stop-Process -Name "WindowsCamera" -ErrorAction SilentlyContinue; $script:rCam="-"; $script:step=1; Next-Step } >> "%PSFILE%"
echo         elseif($step -le 1.5){ $script:rAud="-"; $script:step=2; Next-Step } >> "%PSFILE%"
echo         elseif($step -eq 2){ $script:rLit="-"; $script:step=3; Next-Step } >> "%PSFILE%"
echo     }) >> "%PSFILE%"
echo     $form.ShowDialog() ^| Out-Null >> "%PSFILE%"
echo     $runspace.Dispose() >> "%PSFILE%"
echo } catch { $_ ^| Out-File "%ERRFILE%" } >> "%PSFILE%"

echo [4/5] Levantando UI Inmediata...
powershell -NoProfile -ExecutionPolicy Bypass -File "%PSFILE%"

if exist "%PSFILE%" del "%PSFILE%"
if exist "%LOGOFILE%" del "%LOGOFILE%"
if exist "%WIFIXML%" del "%WIFIXML%"
if exist "%BATTXML%" del "%BATTXML%"

echo.
echo ===========================================
echo   PROCESO FINALIZADO
echo ===========================================
echo.
